"""Create reproducible figures and the factual fractal-marker report."""
from pathlib import Path
import os,json
import numpy as np
ROOT=Path(__file__).resolve().parent
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'plot-cache'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.ticker import MaxNLocator
def main():
    a=json.loads((ROOT/'analysis.json').read_text());carpet=np.load(ROOT/'construction.npz');quarter=np.load(ROOT/'quarter-construction.npz');menger=np.load(ROOT/'menger-construction.npz')
    fig=plt.figure(figsize=(11,8),layout='constrained');ax=fig.add_subplot(221);mask=np.zeros((81,81));c=carpet['level4'];mask[c[:,0],c[:,1]]=1;ax.imshow(mask.T,origin='lower',cmap='Blues',extent=(0,1,0,1),interpolation='nearest');ax.set(title='Random eight-of-nine carpet: stage 4',xlabel='x / initial side',ylabel='y / initial side')
    ax=fig.add_subplot(222);intervals=np.array([[0.,1.]])
    for d in range(7):
        ax.add_collection(LineCollection([[(l,-d),(r,-d)] for l,r in intervals],colors='#246bce',linewidths=4));intervals=np.array([[l,l+(r-l)/3] for l,r in intervals]+[[r-(r-l)/3,r] for l,r in intervals])
    ax.set(xlim=(-.02,1.02),ylim=(-6.6,.6),title='Cantor reference: repeated middle-third removal',xlabel='Position',ylabel='Construction stage');ax.set_yticks(-np.arange(7),np.arange(7))
    ax=fig.add_subplot(223)
    for d in range(1,6):ax.add_collection(LineCollection([[(l,-d),(r,-d)] for l,r in quarter['level'+str(d)]],colors='#d57923',linewidths=5))
    ax.set(xlim=(-.02,1.02),ylim=(-5.6,-.4),title='Random second/third-quarter removal',xlabel='Position',ylabel='Construction stage');ax.set_yticks(-np.arange(1,6),np.arange(1,6))
    ax=fig.add_subplot(224,projection='3d');filled=np.zeros((9,9,9),bool);c=menger['menger2'];filled[c[:,0],c[:,1],c[:,2]]=True;ax.voxels(filled,facecolors='#539dc0',edgecolor='#234758',linewidth=.15);ax.set(title='Menger sponge: stage 2 (400 cells)',xlabel='x cell',ylabel='y cell',zlabel='z cell');fig.suptitle('Reference constructions | marker geometry, not holes cut in the fluid');fig.savefig(ROOT/'reference-patterns.png',dpi=130);plt.close(fig)
    selected=[('carpet4','Random carpet','n64_half.npz',slice(512,4608)),('quarter10','Random intervals','quarter-n64_half.npz',slice(256,1280)),('menger2','Menger sponge','menger-n64_half.npz',slice(0,400))]
    fig=plt.figure(figsize=(11,10))
    fig.subplots_adjust(left=.06,right=.94,bottom=.07,top=.92,wspace=.30,hspace=.28)
    for j,(key,title,file,sl) in enumerate(selected):
        z=np.load(ROOT/file);p=z['positions'][:,sl];ax=fig.add_subplot(2,2,j+1,projection='3d');step=max(1,p.shape[1]//1000)
        ax.scatter(*p[0,::step].T,s=2,c='#246bce',alpha=.45,label='Start');ax.scatter(*p[-1,::step].T,s=2,c='#d57923',alpha=.5,label='Time 0.10');ax.set(title=title,xlabel='x',ylabel='y',zlabel='z');ax.legend(fontsize=7)
        for axis in (ax.xaxis,ax.yaxis,ax.zaxis):axis.set_major_locator(MaxNLocator(3))
        ax.tick_params(labelsize=8,pad=1)
    ax=fig.add_subplot(224);ax.axis('off');ax.text(.05,.75,'Blue: initial positions\nOrange: model time 0.10\n\nUnchanged 64-grid velocity field\nRK4 tracking step: 0.000078125\n\nSelected labels shown for readability.\nAxes use simulation length units.',va='top',fontsize=12,linespacing=1.7)
    fig.suptitle('Passive advection in the original 64-grid flow | selected marker views');fig.savefig(ROOT/'advected-patterns.png',dpi=140,bbox_inches='tight',pad_inches=.3);plt.close(fig)
    fig,axs=plt.subplots(1,3,figsize=(12,4.3),layout='constrained')
    for ax,(key,title,_,_) in zip(axs,[selected[0],selected[1],('menger3','Menger sponge','',None)]):
        for run,t,style,label in [('n64_half','0.0',':','Initial'),('n64_half','0.1','-','64 grid at 0.10'),('n128','0.1','--','128 grid at 0.10')]:
            p=a['profiles'][key][run][t]['3d'];s=np.array(p['local_slopes']);x=np.arange(6)+.5;ax.plot(x,s.mean(axis=0),style,label=label);ax.fill_between(x,s.min(axis=0),s.max(axis=0),alpha=.12)
        ax.set(title=title,xlabel='Scale level (smaller boxes to right)',ylabel='Finite-scale local count slope');ax.grid(alpha=.2);ax.legend(fontsize=7)
    fig.suptitle('Box-count slopes vary with scale | bands span four grid-origin shifts');fig.savefig(ROOT/'finite-scale-slopes.png',dpi=150);plt.close(fig)
    fig,axs=plt.subplots(1,2,figsize=(10,4.2),layout='constrained')
    for ax,g,title in zip(axs,['central','periodic_join'],['Existing central labels','Existing join labels']):
        for n,style in [('reference','-'),('grid128_refined','--')]:
            for t,color in [('0.0','#777777'),('0.1','#246bce'),('0.3','#d57923')]:
                p=a['existing_patterns'][n][g][t]['3d'];c=np.array(p['count']);ax.plot(p['k'],c.mean(axis=0),style,color=color,label=f"{64 if n=='reference' else 128} grid, t={t}")
        ax.axhline(125,color='.4',ls=':',lw=1);ax.set(title=title,xlabel='Scale level (smaller boxes to right)',ylabel='Occupied 3D boxes');ax.legend(fontsize=7);ax.grid(alpha=.2)
    fig.suptitle('Existing 125-label clouds saturate at their finite sample count');fig.savefig(ROOT/'existing-box-counts.png',dpi=150);plt.close(fig)
    text=['# Fractal marker tests: carpet, random intervals and Menger sponge','','**All three marker patterns were followed through model time 0.10 in the unchanged fluid. The counting controls reproduce the known constructions. The finite moving samples do not establish that the fluid itself generates a fractal.**','','[Individual-marker stress test](../README.md) · [Main study](../../README.md)','','## What was tested','','| Construction | Tracked sample sizes | Known ideal dimension |','| --- | ---: | ---: |','| Random eight-of-nine carpet | 512 and 4096 | log(8)/log(3) = 1.892789 |','| Random second/third-quarter removal | 256 and 1024 | log(phi)/log(2) = 0.694242 |','| Menger sponge, the selected “fractal cheese” | 400 and 8000 | log(20)/log(3) = 2.726833 |','| Cantor set: counting-method reference only | 256 reference points | log(2)/log(3) = 0.630930 |','','The finest tracked groups contain 13,120 labels, with coarser sampling controls alongside them. They start in a central region of side0.375. Carpet labels lie in an x-y square, interval labels lie along x, and sponge labels occupy three dimensions. Missing labels do not remove water or create solid walls. All follow `dX_i/dt=u_h(X_i,t)`; there is no added force, noise or replacement Navier–Stokes equation.','','![Reference patterns](reference-patterns.png)','','## The random-interval detail','','One seeded coin flip per stage chooses second-quarter or third-quarter removal in every current connected interval. Each parent leaves **two** connected pieces of lengths one-quarter and one-half. Thus the dimension relation is `(1/4)^d+(1/2)^d=1`, giving d=log(phi)/log(2). Swapping their left/right placement leaves those contraction ratios unchanged. The retained total length after n stages is `(3/4)^n`.',f"The seed551 realization deleted quarters {a['quarter_reference']['deleted_quarter_by_stage']} at successive stages.",'','The first implementation mistakenly treated the three surviving quarter-cells as separate children. That excluded quarter subset and its source are preserved locally as an audit record. The corrected `quarter_connected.py` and its trajectories supply every random-interval result reported here. The independently advected Menger labels from the first batch were retained without repeating them.','','## What the flow did','','![Advected patterns](advected-patterns.png)','','Each pattern is carried and deformed by the flow. These are markers seeded in an already fractal construction: observing their holes is not evidence that the fluid created those holes. Plots show selected physical positions in three dimensions, not a two-dimensional autonomous phase portrait. All lengths, velocities and times use the original model units.','','| Finest marker pattern | Tracking half-step max difference | 64/128 grid max difference | Final shape RMS after centroid alignment | Coarser saved-time max difference |','| --- | ---: | ---: | ---: | ---: |']
    for key,label in [('carpet4','Random carpet'),('quarter10','Random intervals'),('menger3','Menger sponge')]:
        c=a['comparisons'][key];text.append(f"| {label} | {c['tracking_step']['maximum_position_difference']:.3g} | {c['fluid_grid']['maximum_position_difference']:.6f} | {c['fluid_grid']['final_centroid_aligned_shape_rms']:.6f} | {c['snapshot_spacing']['maximum_position_difference']:.6f} |")
    text+=['','The tracking step has little effect over this short window. Grid differences are much larger, even after removing cloud translation. Saved-time coarsening also changes the tracks. The two fluid grids have different sampled starts and preserved means; this is a sensitivity comparison, not a clean convergence proof. The original join mismatch and unresolved spin peaks remain.','','## Box counting: what changes and what does not','','![Finite-scale slopes](finite-scale-slopes.png)','','We count occupied 3D boxes and x-y projection squares at seven scales, with four grid-origin shifts. Each cloud is centered to remove translation; its original0.375 length scale is held fixed. No best-looking interval was selected after seeing the results: fits use levels1–3 and2–4. The raw counts, adjacent-scale slopes, shifted-grid fits, point-count saturation and both sample depths are in [analysis.json](analysis.json).','','| Finest sample at time0.10 | 64-grid 3D slope range, levels1–3 | 128-grid 3D slope range, levels1–3 |','| --- | ---: | ---: |']
    for key,label in [('carpet4','Random carpet'),('quarter10','Random intervals'),('menger3','Menger sponge')]:
        vals=[]
        for n in ['n64_half','n128']:
            s=[v['slope'] for v in a['profiles'][key][n]['0.1']['3d']['fits']['1-3']];vals.append(f'{min(s):.3f}–{max(s):.3f}')
        text.append(f"| {label} | {vals[0]} | {vals[1]} |")
    text+=['','These are **finite-scale fitted slopes**, not new limiting fractal dimensions. Their dependence on scale, origin and sampling is visible. Even the undeformed finite patterns can give shifted-grid fits different from their known ideal dimensions. Every finite point sample eventually saturates and has box dimension0 as boxes become arbitrarily small. A smooth finite-time flow with a Lipschitz inverse preserves an ideal set’s box dimension, although its finite-scale geometry can change. See [box-dimension definition](https://www.math.stonybrook.edu/~scott/Book331/Fractal_Dimension.html) and [bi-Lipschitz invariance](https://link.springer.com/article/10.1007/s00209-019-02426-2).','','## Existing marker patterns','','![Existing counts](existing-box-counts.png)','','The original stress-test clouds contain125 markers each. Their counts saturate at that sample size across the tested scales. This data does not establish a scale-independent fractal dimension. The full3D counts and2D projection counts are kept separate.','','## Verification, limits and reproduction','','Construction-aligned counts exactly reproduce the carpet, Cantor, Menger, filled-line and filled-square benchmarks over their construction scales. For the unequal random intervals, every stage passes the retained-length and sum-of-lengths-to-the-d checks. Every trajectory file is finite-checked and hashed; initial interpolation agrees with an independent SciPy sampler. The fluid fields and numerical source were preserved. These checks concern implementation consistency, not physical fractal convergence.','','The marker patterns include separations below a fluid grid cell. Interpolation can place and move those labels, but cannot supply missing small-scale fluid detail. This batch does not demonstrate molecular interactions, a strange attractor, a chaos theorem, sustained breathing or Navier–Stokes blowup.','','Run `python analyze_fractals.py` and `python report_fractals.py` with the supplied data to rebuild the analysis and figures. Tracking scripts require the original saved fluid fields. The Menger-only reproduction entry point is `menger_tracks.py`; the saved Menger tracks were extracted losslessly from the historical independent-label batch. [Verification](verification.json) and the [protocol addendum](protocol-addendum.json) record these checks and the corrected random-interval construction. [Menger construction reference](https://www.math.uwaterloo.ca/~ervrscay/courses/amath343docs/week10.pdf). The user’s textbook images and private documents are not included.','']
    s='\n'.join(text)
    for old,new in [('side0.375','side 0.375'),('seed551','seed 551'),('original0.375','original 0.375'),('levels1','levels 1'),('and2','and 2'),('time0.10','time 0.10'),('dimension0','dimension 0'),('contain125','contain 125'),('full3D','full 3D')]:s=s.replace(old,new)
    (ROOT/'README.md').write_text(s,encoding='utf-8');print('Fractal report and four figures complete.')
if __name__=='__main__':main()
