"""Final report for the existing 17-run driven matrix; requires all jobs complete."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parent
def main():
    a=json.loads((ROOT/'fluid-analysis.json').read_text());assert a['completed']==17 and a['status']=='complete'
    verified=json.loads((ROOT/'fluid-field-verification.json').read_text());assert len(verified)==17
    force=json.loads((ROOT/'forcing-verification.json').read_text());assert force['status']=='passed' and force['driver_sha256']==hashlib.sha256((ROOT/'run_fluid.py').read_bytes()).hexdigest()
    predictions=a['predictions'];held=[v for v in predictions.values() if not v['training'] and not v['mirror_of_training']]
    assert held
    errors=[v['relative_curve_error'] for v in held];pair=max(v['max_field_relative_error'] for v in a['pairs'].values())
    fields=sum(v['fields_checked'] for v in verified.values());max_endpoint=max(v['max_endpoint_scaled_error'] for v in verified.values())
    zero=a['runs']['n49-even-gap-A0.5-P0.2-s0-base'];zr=json.loads((ROOT/'fluid-runs/n49-even-gap-A0.5-P0.2-s0-base/result.json').read_text());zero_E=max(v['E'] for v in zr['dense']);zero_D=max(abs(v['D']) for v in zr['dense'])
    summary=dict(status='complete_verified',runs=17,fields_verified=fields,max_endpoint_scaled_error=max_endpoint,full_field_mirror_error=pair,zero_bias_max_E=zero_E,zero_bias_max_abs_D=zero_D,held_out_predictions=len(held),held_out_error_range=[min(errors),max(errors)],predictions_passing_10_percent=sum(v['passes_10_percent'] for v in held),source_driver_sha256=force['driver_sha256'],prediction_protocol_sha256=hashlib.sha256((ROOT/'prediction-protocol.json').read_bytes()).hexdigest(),limitation='Minimum transverse half-peak widths are below six cells. No resolved-peak or continuum regularity conclusion.')
    (ROOT/'fluid-report-verification.json').write_text(json.dumps(summary,indent=2)+'\n')
    lines=['# Completed driven-fluid comparison','','**All 17 runs reached time 0.40. The prescribed reflection tests passed. The two tested scalar-to-fluid mappings failed the prediction check. The spin peak remains under-resolved.**','','This completes the fluid portion of the [model-layer study](README.md). Four reduced layers were already computed separately. Here the measured fluid trajectories test one fixed quantitative mapping from the scalar ball model, plus the symmetry consequences of the chosen forcing patterns.','','## What was run','','- Same mirrored starting construction, periodic cube side 6, viscosity 0.01 and Heun stepping.','- Initial lean is plus or minus 1% of the baseline velocity norm; one control has zero lean.','- Mirror-even gap drive or mirror-odd lean drive; amplitudes A = 0.15 and 0.5, periods P = 0.2 and 0.1.','- Six reflected pairs at 49 cubed; strong-drive 65-grid and half-timestep controls for both drive types; one even-drive zero-bias control.','','The acceleration is `F(t) = A*U0/0.4*sin(2*pi*t/P)*unit_template`. It is integrated with dt at both Heun stages. The original unforced studies are separate. The older breathing upload used an unscaled per-step velocity kick; its results are not a timestep control for this new equation.','','E = norm(u − M[u])/norm(u) is unsigned. D = mean((u − M[u])·phi) is the signed projection onto the unit antisymmetric template. U0 is the initial baseline velocity norm. W is maximum vorticity magnitude, and I is its time integral. Energy = one half the integral of speed squared; enstrophy = one half the integral of vorticity squared. Units are model units.','','## Observed fluid response','','![Fluid curves](fluid-curves.png)','','| Drive | Grid | A | P | Initial sign | Step | Final D | Final E | Final W | Final I |','| --- | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: | ---: |']
    for name,v in sorted(a['runs'].items()):
        j=v['job'];f=v['final'];lines.append(f"| {j['parity']} | {j['n']} | {j['A']} | {j['P']} | {j['sign']} | {'half' if j['half'] else 'base'} | {f['D']:.7f} | {f['E']:.7f} | {f['W']:.5f} | {f['I']:.5f} |")
    lines+=['','The even gap drive has no direct projection onto signed D to numerical precision. It still changes the velocity field and can change later D through evolution. The odd drive directly supplies a signed contribution; its reflected counterpart reverses the force as well as the starting lean.','','At A = 0.5 and P = 0.2, the positive odd-drive run ends with negative D while E remains nonzero. Reversing the whole experiment gives opposite D and equal E. This is a forced directional response; it does not show spontaneous side selection from an unsigned start.','','## Prediction test','','The [prediction protocol](prediction-protocol.json) was fixed before the low-amplitude odd-drive training run completed. Only that positive run, A = 0.15 and P = 0.2 at 49 cubed, fits the nonnegative scale k. The reflected training run is a symmetry check, not an independent unseen case.','','Two ball candidates use `x\'\' = r*x − x^3 − 0.4*x\' + sign*A*sin(2*pi*t_ball/(20*P))`, with r = −1 or +1 and `t_ball = 20*t_fluid`. The fixed mapping is `predicted D/U0 = initial D/U0 + k*(x − x0)`, with x0 = sign*0.1. No coefficient or time scale is adjusted to held-out results.','','| Candidate r | Fitted k | Training curve error |','| --- | ---: | ---: |']
    for r in (-1,1):
        fit=a['fits'][str(r)];train=next(v for v in predictions.values() if v['training'] and v['r']==r);lines.append(f"| {r} | {fit['k']:.8f} | {100*train['relative_curve_error']:.3f}% |")
    lines+=['','![Unseen forcing predictions](fluid-predictions.png)','','| Positive held-out run | r = −1 error | r = +1 error | Constant baseline error | Linear baseline error |','| --- | ---: | ---: | ---: | ---: |']
    positive=sorted({v['run'] for v in held if '-s1-' in v['run']})
    for name in positive:
        neg=predictions['r-1 '+name];pos=predictions['r1 '+name];lines.append(f"| {name} | {100*neg['relative_curve_error']:.3f}% | {100*pos['relative_curve_error']:.3f}% | {100*pos['constant_error']:.3f}% | {100*pos['linear_error']:.3f}% |")
    lines+=['',f"All {len(held)} held-out candidate/run scores exceed the fixed 10% exploratory threshold. The fitted r = −1 scale is zero, so that predictor reduces to the constant baseline. The r = +1 mapping also misses the fluid curve substantially. These results reject predictive use of these particular mappings and parameters.",'','This does not test every possible reduced model. A numerical mapping for the four-node coupling, listening feedback and scalar diffusion coefficients has not been defined. Their reduced-model results and structural symmetry checks remain separate evidence. No fitted q feedback is applied to the fluid.','','## Grid and timestep controls','','| Comparison | W error | I error | E error | D error | Energy error | Enstrophy error |','| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    for name,v in a['comparisons'].items():lines.append('| '+name+' | '+' | '.join(f"{100*v[k]:.6f}%" for k in ('W','I','E','D','energy','enstrophy'))+' |')
    lines+=['','Errors are relative L2 differences between curves interpolated to common times in [0, 0.4], using the finer grid or smaller step as reference. Close D or E curves do not establish a resolved spin maximum.','','| Positive strong drive | Grid | Step | Smallest width (cells) | Largest upper-band enstrophy | Largest energy-budget residual |','| --- | ---: | --- | ---: | ---: | ---: |']
    for name,v in sorted(a['runs'].items()):
        j=v['job']
        if j['A']==.5 and j['P']==.2 and j['sign']==1:lines.append(f"| {j['parity']} | {j['n']} | {'half' if j['half'] else 'base'} | {v['min_width_cells']:.4f} | {100*v['max_tailZ']:.5f}% | {100*v['max_energy_balance']:.7f}% |")
    lines+=['','Width is the shortest of 12 transverse half-peak chords through the current spin maximum, sampled by interpolation and expressed in grid cells. The six-cell width screen fails. The physical width is cells times 6/N. Spectral fractions refer to the upper 20% of retained component modes.','','Energy accounting includes force work and viscous loss. Raw Meter vorticity/velocity RHS entries contain the unforced terms only; [extended diagnostics](fluid-extended-diagnostics.json) add force and curl(force) at the same peak location. This batch does not include an independently integrated, fully forced enstrophy budget at every time step.','','## Verification','','- All saved fields are finite and their hashes match the run manifests.',f'- {fields} saved fields checked; independently remeasured endpoints agree within {max_endpoint:.3g} in the stated scaled error.',f'- Six reflected full-field pairs agree to relative error {pair:.3g}.',f'- Zero-bias even-force control: maximum E = {zero_E:.3g}; maximum |D| = {zero_D:.3g}.','- The analytic forced-shear check shows approximately fourfold error reduction when dt is halved, consistent with second-order stepping.','- Divergence, energy balance and speed-CFL checks passed for all 17 runs.','','[Run records](fluid-runs/) · [Analysis and prediction scores](fluid-analysis.json) · [Field verification](fluid-field-verification.json) · [Report verification](fluid-report-verification.json) · [Analytic forcing check](forcing-verification.json)','','## Reproduction','','Install `requirements.txt`. `python run_fluid.py` executes exactly the 17 listed jobs, or resumes saved checkpoints. For a fresh computation, copy the Python scripts, protocols, requirements and source directory into a new folder; omit the published fluid-runs measurement directory. Those published records mark completed jobs but do not include the raw arrays needed for resuming or reanalysis. `python analyze_fluid.py` measures completed results and applies the frozen prediction protocol. After all jobs complete, `python report_fluid.py` rebuilds this report. `python check_forcing.py` runs the separate exact-shear implementation check.','','Measurement records, code and figures are published on GitHub and copied to the local repository mirror. Large raw restart arrays stay in the local study; their SHA256 identities are included in each run record.','']
    (ROOT/'FLUID.md').write_text('\n'.join(lines),encoding='utf-8');print(json.dumps(summary))
if __name__=='__main__':main()
