"""Build the readable report from measured results, without rerunning dynamics."""
from pathlib import Path
import json, base64, html
R=Path(__file__).resolve().parent;D=R/'data'
t=json.loads((D/'toy_results.json').read_text())
m=json.loads((D/'md_results.json').read_text())
p=json.loads((D/'md_protocol.json').read_text())
c=json.loads((D/'md_permutation_control.json').read_text())
v=json.loads((D/'verification.json').read_text())
def image(name):return 'data:image/png;base64,'+base64.b64encode((R/name).read_bytes()).decode()
def f(x,n=3):return f'{x:.{n}f}'
def table(headers,rows):
    return '<table><thead><tr>'+''.join('<th>'+str(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(cell)+'</td>' for cell in row)+'</tr>' for row in rows)+'</tbody></table>'
rep_table=table(['Measurement','Run 1','Run 2','Run 3'],[
    ['Mean force-score CV',*[f(100*r['force_cv_snapshot_mean'],1)+'%' for r in m['replicas']]],
    ['Median strongest / weakest force score',*[f(r['force_max_min_ratio_snapshot_median'],2) for r in m['replicas']]],
    ['Distinct top force-score labels / 10 snapshots',*[str(r['force_unique_leaders'])+'/10' for r in m['replicas']]],
    ['Changes between successive 5 ps force snapshots',*['9/9' for r in m['replicas']]],
    ['Distinct top oxygen-neighborhood labels / 500 frames',*[r['coordination_unique_leaders'] for r in m['replicas']]],
    ['Neighborhood leader changes at 0.1 ps spacing',*[f(100*r['coordination_leader_change_fraction_0.1ps'],1)+'%' for r in m['replicas']]],
    ['Neighborhood rank correlation at 1 ps',*[f(r['coordination_rank_correlation_by_lag_ps']['1.0']) for r in m['replicas']]],
    ['First-half vs second-half mean neighborhood ranks',*[f(r['coordination_first_vs_second_half_mean_spearman']) for r in m['replicas']]],
    ['Mean temperature (K)',*[f(r['temperature_mean_K'],2) for r in m['replicas']]],
    ['Mean potential energy / water (kJ/mol)',*[f(r['potential_per_molecule_mean_kJ_mol'],3) for r in m['replicas']]],
    ['Mean geometric H-bond neighbors',*[f(r['hydrogen_bond_unique_neighbor_mean']) for r in m['replicas']]],
])
ensemble_table=table(['Distance scale ℓ','Periodic: mean CV','Open box: mean CV','Periodic: middle 95% of CVs'],[
    [str(ell),f(100*t['ensembles'][f'periodic_ell_{ell}']['cv_mean'],2)+'%',
     f(100*t['ensembles'][f'open_ell_{ell}']['cv_mean'],2)+'%',
     '–'.join(f(100*x,2)+'%' for x in [t['ensembles'][f'periodic_ell_{ell}']['cv_2.5_50_97.5_percentiles'][0],t['ensembles'][f'periodic_ell_{ell}']['cv_2.5_50_97.5_percentiles'][2]])] for ell in [.12,.18,.3]])
body=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Can identical water molecules acquire unequal influence?</title>
<style>body{{font:17px/1.6 system-ui,sans-serif;max-width:1050px;margin:48px auto;padding:0 28px;color:#172630;background:#fafbfc}}h1{{font-size:37px;line-height:1.2}}h2{{font-size:24px;margin-top:36px}}.tag{{color:#087e83;text-transform:uppercase;letter-spacing:.1em;font-size:12px;font-weight:700}}.lead{{font-size:21px}}.box{{border-left:5px solid #087e83;background:#edf5f5;padding:12px 22px}}img{{width:100%;background:white}}table{{border-collapse:collapse;width:100%;font-size:14px;margin:20px 0}}th,td{{padding:10px 12px;text-align:left;border-bottom:1px solid #d2dce0}}th{{background:#e8eff2}}code,pre{{background:#edf1f3;font-family:Consolas,monospace}}pre{{padding:18px;overflow:auto}}a{{color:#087e83}}.small{{font-size:14px;color:#50616b}}li{{margin:8px 0}}.equation{{padding:14px 20px;background:#edf1f3;font-family:Cambria,Georgia,serif;font-size:19px}}@media print{{body{{margin:0;background:white;font-size:12px}}h2{{break-after:avoid}}img,table{{break-inside:avoid}}}}</style>
<p class="tag">Reproducible computational experiment · 8 October 2026</p>
<h1>Can identical water molecules acquire unequal influence?</h1>
<p class="lead"><strong>Yes, if “influence” means a specified, local response score.</strong> Identical interaction rules produced unequal scores because the surrounding geometry differed. The top-scoring label changed when labels exchanged positions and as water moved. This establishes temporary response heterogeneity; it does not establish one-way control or a permanent hierarchy.</p>
<p>Two experiments were actually run: an exactly solved toy diffusion network and three short atomistic TIP3P water simulations. All numbers below are calculated from the saved data. Neither model contains preferences, intentions, or molecule-specific leadership parameters.</p>
<img src="{image('results.png')}" alt="Four panels showing toy positional scores, label swap, water force-response scores, and changing leaders">
<h2>1. Toy network: isolate position alone</h2>
<p>Place 64 identical point particles independently and uniformly in a three-dimensional unit cube, with periodic boundaries. Their positions remain fixed. Each has one scalar state x; all follow the same linear diffusion equation. A symmetric Gaussian interaction depends only on minimum-image separation. There are no charges, water geometry, excluded volume, hydrogen bonds, molecular motion, or physical units.</p>
<div class="equation">w<sub>ij</sub> = exp[−r<sub>ij</sub>²/(2ℓ²)], w<sub>ii</sub> = 0;<br>dx/dt = −Lx, L = diag(W1) − W; &nbsp; H(t) = exp(−Lt).<br>I<sub>i</sub>(t) = ∑<sub>j ≠ i</sub> H<sub>ji</sub>(t) = 1 − H<sub>ii</sub>(t).</div>
<p>The whole matrix W is divided by its mean row sum, setting a common mean interaction rate of one. Each test starts with the same unit pulse at one source i and zero elsewhere. I is the fraction of that pulse found at other nodes at time t. The primary choices were ℓ = 0.18, t = 0.5 and NumPy seed {t['seed']}; these were set before viewing results. The matrix exponential was evaluated by symmetric eigendecomposition, so there is no time-step integration error.</p>
<p>The primary scores ranged from <strong>{f(t['primary']['minimum'],6)} to {f(t['primary']['maximum'],6)}</strong>, a strongest/weakest ratio of <strong>{f(t['primary']['max_over_min'],3)}</strong>. Mean {f(t['primary']['mean'],6)}, population SD {f(t['primary']['sd'],6)} and coefficient of variation (CV = SD/mean) {f(100*t['primary']['cv'],2)}% describe the dispersion. Label 25 was highest; label 14 was lowest. Labels are zero-based throughout the files and this report.</p>
<p><strong>Position exchange:</strong> exchanging the positions of labels 25 and 14 made label 14 the leader with the same high score. Across 1,000 random position permutations the leading label changed in <strong>{t['checks']['changed_leader_count']}/1,000</strong> trials. The expectation from uniform relabeling is 63/64 = 98.4375%. Every score followed its occupied site; the largest discrepancy was {t['checks']['permutation_max_absolute_error']:.2e}.</p>
<p><strong>Controls:</strong> all 64 particles tied in a periodic 4 × 4 × 4 lattice (score spread {t['controls']['periodic_cubic_lattice']['spread']:.2e}), and under equal all-to-all coupling (spread {t['controls']['equal_all_to_all']['spread']:.2e}). With interactions removed, all off-source responses were zero. These controls show that the ranking depends on unequal surroundings, rather than labels or an arbitrary tie-break. The raw JSON stores an argmax even for tied controls; that index has no scientific meaning.</p>
<p>All 200 additional independently sampled configurations were retained. Each was evaluated at three interaction ranges with both periodic and open boundaries; these are paired conditions on the same configurations. Periodic boundaries remove a distinguished outer surface. At the primary range the mean periodic CV was {f(100*t['ensembles']['periodic_ell_0.18']['cv_mean'],2)}%, with across-configuration SD {f(100*t['ensembles']['periodic_ell_0.18']['cv_sd'],2)} percentage points and standard error {f(100*t['ensembles']['periodic_ell_0.18']['cv_mean_se'],3)} percentage points.</p>
{ensemble_table}
<p class="small">The middle 95% is an empirical distribution interval across 200 configurations, not a confidence interval for the mean. Open boundaries increase the positional inequality, but the effect remains with periodic boundaries.</p>
<p><strong>Observation time matters:</strong> in the same primary configuration the strongest/weakest ratio was 2.417 at t = 0.05, 2.018 at t = 0.5 and 1.064 at t = 5. The leader changed from label 25 at t = 0.5 to label 36 at t = 5. As t → ∞ every score tends to 63/64; at t = 50 the maximum deviation was {t['checks']['long_time_max_error']:.2e}. Because H is symmetric, pairwise pulse transfer is reciprocal (maximum asymmetry {t['checks']['symmetric_response_max_error']:.2e}). Total pulse is conserved to {t['checks']['conserved_impulse_max_error']:.2e}. A particle with a high outgoing score has an equally high incoming score under this measure.</p>
<h2>2. Water simulation: atomistic forces and changing geometry</h2>
<p><strong>This is actual classical molecular dynamics, but still an approximate water model.</strong> OpenMM {p['openmm']} simulated 216 rigid TIP3P molecules at a target 300 K in a periodic cube of side {p['box_side_nm']:.9f} nm. Density was imposed at 0.997 g/cm³; it was not a predicted density or a 1-atmosphere pressure result. Every molecule had identical masses, charges and Lennard–Jones parameters; the saved-system audit checked this directly.</p>
<p>Three runs used seeds 20261008–20261010. They began on the same oxygen sites with independently randomized orientations, initial velocities and thermostat random forces. Each was minimized (up to 2,000 iterations; force tolerance 10 kJ mol⁻¹ nm⁻¹), equilibrated for 20 ps, then sampled for 50 ps. The protocol used NVT Langevin-middle dynamics, 1 ps⁻¹ friction, 2 fs steps, rigid-water constraints with 10⁻⁶ tolerance, and PME electrostatics with 0.8 nm real-space cutoff and 10⁻⁵ Ewald error tolerance. Lennard–Jones switching was off; OpenMM's default dispersion correction was retained. Simulation used OpenCL mixed precision; response measurements used a separate OpenCL double-precision context. The <a href="https://docs.openmm.org/latest/userguide/application/02_running_sims.html">OpenMM guide</a> documents the force fields and PME workflow.</p>
<p><strong>The physical score is an instantaneous force susceptibility.</strong> In each snapshot, molecule i was translated by ±0.0001 nm along each of three axes, moving its three atoms together. The total force on each other molecule j was recomputed, and central differences estimated a 3 × 3 derivative block. Original positions were restored. These probes ran in a separate context and could not disturb the production trajectory.</p>
<div class="equation">K<sub>ji</sub> = ∂F<sub>j</sub>/∂R<sub>i</sub>; &nbsp; S<sub>i</sub> = ∑<sub>j ≠ i</sub> ‖K<sub>ji</sub>‖<sub>F</sub>.</div>
<p>The Frobenius norm combines all nine directional components. S has units kJ mol⁻¹ nm⁻². This measures how much an equal tiny displacement changes other molecules' forces, not long-time control, information flow, or a measured impulse-response trajectory. Strong local repulsion can contribute heavily. Equal displacement also need not inject equal energy into different environments.</p>
<p>Force scores were measured at 5, 10, …, 50 ps in each production run, giving 30 snapshots and 216 tests per snapshot. An auxiliary position-only neighborhood score was sampled every 0.1 ps: C<sub>i</sub> = ∑<sub>j ≠ i</sub> exp[−½((r<sub>OO,ij</sub> − 0.28 nm)/0.05 nm)²]. This is a smooth oxygen-neighborhood proxy, not a physical force or hydrogen-bond measure. Hydrogen-bond neighbor counts were recorded separately using O–O &lt; 0.35 nm and an O→H/O→O angle &lt; 30°, counting distinct neighbors without direction. Such geometric definitions affect network statistics, as shown by <a href="https://pubmed.ncbi.nlm.nih.gov/25481129/">Ozkanlar, Zhou &amp; Clark (2014)</a>.</p>
{rep_table}
<p>Each run had ten different top force-score labels across ten snapshots: all <strong>27 of 27</strong> within-run adjacent comparisons changed leader. This is turnover at the sampled times, not a measured leader lifetime. Neighborhood ranks also lost most correlation over roughly 1 ps under this particular model and metric. The mean rank correlations between the physical and neighborhood scores were 0.289, 0.251 and 0.247; counting nearby oxygen atoms is therefore a weak substitute for the force-response calculation.</p>
<p><strong>Molecular coordinate permutation:</strong> in run 1's 50 ps snapshot, all O/H/H coordinate blocks were randomly reassigned among labels. This preserved every occupied atomic position and orientation in the unlabeled configuration. The top label changed from <strong>{c['base_leader']} to {c['permutation_new_leader']}</strong>, exactly the label moved into the original top molecule's complete pose. The entire response vector agreed with the predicted permutation to relative L2 error <strong>{c['permutation_relative_L2_difference']:.2e}</strong> (Spearman correlation 1); total potential energy changed by only {c['permutation_energy_difference_kJ_mol']:.2e} kJ/mol.</p>
<div class="box"><strong>What that permutation does and does not establish.</strong> For identical molecules, reassignment of complete coordinate blocks is a symmetry, equivalent to relabeling the same physical arrangement. It is a useful implementation check, not independent statistical proof of emergent leadership. Swapping only oxygen centers while retaining each label's original orientation creates a different atomic configuration and can introduce unfavorable contacts. That intervention was not performed. The water result concerns all atomic positions, including orientation; it does not establish dependence on oxygen-center positions alone.</div>
<h2>3. Numerical checks and physical limitations</h2>
<p>An initial mixed-precision force-difference calculation failed the planned 1% aggregate convergence check (1.094% difference on halving the displacement). Those force scores were discarded, and the reported water experiment was rerun using double precision for the force probes. In the reported run, halving the displacement changed the score vector by <strong>{100*c['half_step_relative_L2_difference']:.4f}%</strong> in relative L2 norm; the largest individual relative change was <strong>{100*c['half_step_max_relative_difference']:.2f}%</strong>. The leader was unchanged and rank correlation was {c['half_step_spearman']:.6f}. Thus the result is numerically robust at the reported precision, but the finite-difference scores are not exact derivatives.</p>
<p>The maximum full-Jacobian reciprocity error ‖K − Kᵀ‖/‖K‖ across the 30 snapshots was {100*max(r['force_jacobian_reciprocity_error_max'] for r in m['replicas']):.3f}%. A conservative potential implies reciprocal cross derivatives in the exact smooth limit; the finite-difference and finite-cutoff calculation leaves a small residual. The score therefore describes strength of coupling in both directions, not unilateral authority. Parameter identity, finite arrays, all 648 constraints, score reconstruction from the saved Jacobian, and coordinate-permutation agreement passed the included audit.</p>
<img src="{image('diagnostics.png')}" alt="Temperature, potential energy, oxygen pair distribution and decay of neighborhood rank correlation">
<p>The oxygen radial-distribution first peak was at {m['rdf_first_peak_nm']:.3f} nm with height {m['rdf_first_peak_height']:.3f}. Mean temperatures were 298.92, 303.82 and 300.40 K. First-to-second-half changes in mean potential energy per molecule were −0.240, +0.168 and −0.084 kJ/mol. These are sanity checks, not a demonstration of full equilibration or quantitative agreement with experimental water.</p>
<ul><li><strong>Finite sampling:</strong> 216 molecules and 50 ps production per run are small and short. Frames and molecules are correlated. No p-values or confidence intervals based on treating all frames or molecules as independent are claimed. The three-run ranges describe observed variability, not universal bounds.</li>
<li><strong>Model fidelity:</strong> rigid TIP3P is atomistic, fixed-charge and nonpolarizable. It omits flexible internal motion, electronic response, nuclear quantum effects, bond breaking and proton transfer. Physical water properties vary substantially between models; <a href="https://arxiv.org/abs/0901.1803">Vega et al. (2009)</a> compare these limitations. No claim of full physical fidelity is made.</li>
<li><strong>Metric dependence:</strong> ranking any fluctuating quantity produces a maximum. Nonzero dispersion and symmetry controls are more informative than the mere existence of a winner. A different response horizon, perturbation normalization, rotational perturbation, or target observable could produce a different ordering.</li>
<li><strong>Persistence:</strong> the findings support transient roles and provide no evidence here for a permanent privileged molecular identity. Short simulations cannot prove that every label will have exactly equal time-averaged scores in the long run.</li>
<li><strong>Permutation logic:</strong> the labeling symmetry is guaranteed by identical molecular parameters. It does not require molecular dynamics, and it cannot by itself validate the proposed interpretation.</li></ul>
<h2>4. Next validation steps</h2>
<ol><li>Repeat with longer independently equilibrated runs, at least two larger box sizes, smaller time steps and varied thermostat friction. Check pressure, diffusion and structural observables. Use independent-run or time-block uncertainty estimates and a held-out interval for persistence tests.</li>
<li>Repeat using a better-performing alternative water model such as TIP4P/2005; use a polarizable or quantum treatment if those effects are central. Verify that the qualitative result survives the force field, rather than comparing only raw score magnitudes.</li>
<li>Run paired perturbed/unperturbed trajectories from saved states, with matched stochastic forcing, several perturbation amplitudes, equal-energy or momentum-balanced perturbations, and horizons such as 0.01, 0.1 and 1 ps. Compare displacement/velocity response of other molecules, controlling for injected energy and center-of-mass motion.</li>
<li>Test rotational perturbations and controlled changes in local geometry; distinguish changes in oxygen position from changes in orientation. Smooth or vary cutoffs and tighten electrostatics to reduce the residual Jacobian error.</li>
<li>If the claim is a directional hierarchy, define and test a directional observable explicitly. The reciprocal models used here cannot turn aggregate coupling strength into one-way dominance.</li></ol>
<h2>5. Reproduce and inspect</h2>
<p>The bundle includes complete source, pinned package versions, initial topology, the serialized force-field system, equilibrated states, all 1,500 saved atomic-coordinate frames, force-score arrays, two saved force Jacobians, CSV summaries, and figures. Molecule i occupies atoms 3i, 3i+1, 3i+2 in O/H/H order. Coordinate units are nm; production frames are 0.1–50 ps, with force scores at 5–50 ps. Run numbers in figures are 1–3; file suffixes are 0–2.</p>
<pre>python -m pip install -r requirements.txt
# Rerun the toy test only:
python experiment.py --mode toy --out reproduced
# Rerun both experiments (portable CPU; force probes use Reference):
python experiment.py --mode all --platform CPU --out reproduced
# The recorded run used an OpenCL device supporting double precision:
python experiment.py --mode all --platform OpenCL --out reproduced
# Reanalyze the delivered coordinate data without rerunning dynamics:
python experiment.py --mode analyze --out data
python verify_outputs.py
python make_figures.py
python build_report.py</pre>
<p>Python 3.12.14, NumPy {p['numpy']}, SciPy 1.18.1 and OpenMM {p['openmm']} were used on Windows. Toy results reproduce to floating-point tolerance. Molecular trajectories can diverge across hardware or reruns even with the same seeds: OpenMM <a href="https://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinMiddleIntegrator.html">explicitly does not promise identical trajectories from a reused seed</a>. Saved trajectories make the reported structural analysis exactly repeatable to numerical tolerance. Force scores can be recomputed from the stored snapshots with <code>force_sensitivity</code>; the two saved Jacobians allow the permutation comparison to be audited directly. Check <code>manifest_sha256.json</code> for file hashes.</p>
<p class="small">Source context: the referenced conversation exposed the user's prompts but not the full prior assistant replies. This experiment operationalizes the current request independently; no earlier unverified claims were treated as results.</p>
</html>'''
(R/'report.html').write_text(body,encoding='utf-8')
print('Report saved.')
