"""Build figures and a report from the completed first-change audit."""
from pathlib import Path
import json, os
import numpy as np
ROOT=Path(__file__).resolve().parent
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'plot-cache'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
def main():
    a=json.loads((ROOT/'results.json').read_text());assert a['status']=='complete'
    starts=a['starts'];hist=a['histories'];steps=a['steps']
    cases=[('ab','AB'),('ab_cd','AB + equal CD'),('mirror-33-1','+1% lean'),('mirror-33--1','-1% lean'),('ab_c','AB + C'),('ab_c_mirror','AB + mirror C'),('ab_uneven','AB + 70/30 CD')]
    fig,axs=plt.subplots(1,2,figsize=(12,5.5),layout='constrained');y=np.arange(len(cases))
    colors=['#557aa0','#557aa0','#c25b32','#488b84','#c25b32','#488b84','#9c6eaa']
    axs[0].barh(y,[starts[k]['after_projection']['E'] for k,l in cases],color=colors);axs[0].set_xscale('log');axs[0].set_xlim(1e-17,.1);axs[0].set_title('E: unsigned mirror difference');axs[0].set_xlabel('E at time zero');axs[0].set_yticks(y,[l for k,l in cases]);axs[0].invert_yaxis();axs[0].grid(axis='x',alpha=.2)
    axs[1].barh(y,[starts[k]['after_projection']['D'] for k,l in cases],color=colors);axs[1].axvline(0,color='black',lw=1);axs[1].set_title('D: signed projection');axs[1].set_xlabel('D at time zero');axs[1].set_yticks(y,[l for k,l in cases]);axs[1].invert_yaxis();axs[1].grid(axis='x',alpha=.2)
    fig.suptitle('Where the first difference enters | before fluid evolution\n33 cubed; identical diagnostic definitions; AB and equal CD remain symmetric')
    fig.savefig(ROOT/'initial-differences.png',dpi=160);plt.close(fig)
    fig,axs=plt.subplots(2,3,figsize=(14,8),layout='constrained')
    groups=[ [('mirror-49-1','Unforced +1% lean'),('new-drive-even-gap','Mirror-even force'),('new-drive-odd-lean','Mirror-odd force')], [('mirror-33-1','Unforced +1% lean'),('old-breathing-small lean','Original breathing kick')] ]
    for j,group in enumerate(groups):
        for key,label in group:
            rows=[v for v in hist[key]['rows'] if v['t']<=.04+1e-12]
            for ax,k in zip(axs[j],('D','E','W')):ax.plot([v['t'] for v in rows],[v[k] for v in rows],label=label,marker='.' if key.startswith('mirror') else None)
        for ax,k in zip(axs[j],('D','E','W')):ax.set(title=k,xlabel='Model time');ax.grid(alpha=.2);ax.legend(fontsize=8)
    axs[0,0].set_ylabel('49 cubed: new force controls');axs[1,0].set_ylabel('33 cubed: original kick')
    fig.suptitle('Early response after the same signed start in each row\nSeparate drive rules and grids; each curve uses its actual saved times')
    fig.savefig(ROOT/'early-response.png',dpi=160);plt.close(fig)
    lines=['# Where each experiment first changes','','**The signed lean and unmatched C alter the starting field. Breathing alters the stepping rule. Matched stretch uses a separate starting field.**','','This audit reconstructs 23 first steps and checks them against available saved fields or measurement records. It reuses completed histories and refinement audits. No long run was restarted. Here, “difference” means a changed experiment; the spatial divergence error separately measures incompressibility.','','## Choices and errors','','A different start or an added drive is an experimental choice. Describing a per-step velocity kick as a timestep-independent force is an error: reducing the timestep applies more kicks over the same interval. The newer driven controls integrate a prescribed acceleration at both Heun stages. Their amplitude, period, normalization and grids are separately specified; they are not an exact replacement of the old breathing experiment.','','| Experiment | First change | Equation after initialization |','| --- | --- | --- |','| Exact AB or equal mirrored CD | No imposed mirror-odd part | Unforced Navier–Stokes |','| Positive/negative lean | Add a signed antisymmetric field at time zero | Unforced Navier–Stokes |','| Unmatched C, or unequal C/D | Change the starting geometry at time zero | Unforced Navier–Stokes |','| Original breathing | Add a velocity kick before each fluid step | Driven discrete update |','| New breathing controls | Add force at both Heun stages | Forced Navier–Stokes approximation |','| Matched stretch | Replace the start with tube plus aligned strain | Unforced Navier–Stokes |','','## Starting measurements','','E = norm(u − M[u]) / norm(u). D = mean((u − M[u]) · phi), where phi is the normalized mirror-odd template. D retains a direction; E is nonnegative. D has velocity units with this normalization; E is dimensionless. W is maximum vorticity magnitude. Other quantities use model units.','','| Start, 33 cubed | E(0) | D(0) | W(0) |','| --- | ---: | ---: | ---: |']
    for k,label in cases:
        r=starts[k]['after_projection'];lines.append(f"| {label} | {r['E']:.6g} | {r['D']:.6g} | {r['W']:.5f} |")
    lines+=['','![Starting differences](initial-differences.png)','','The opposite leans already have opposite D before evolution. Equal CD cancels the mirror-odd part at initialization. Unmatched C has E = 0.0287545 initially. In its saved unforced run E first decreases, then reaches 0.0329282 at time 0.5, while D falls from 0.00593477 to 0.00379039 and W falls from 14.78463 to 11.04645. An increase in normalized E does not itself mean an increasing spin peak.','','## First breathing step','','**Original driver:** `u <- u + 0.15*sin(2*pi*t/0.4)*gap_field`, then the unforced fluid step. The kick is not multiplied by dt. Its first application is at t = dt, not at zero.','','**New drive:** `F(t) = A*U0/0.4*sin(2*pi*t/P)*unit_template`, included as acceleration at both Heun stages. F(0) = 0, but the second stage of the first step uses F(dt).','','| Case | dt | Relative field difference from one unforced step | Direct signed contribution |','| --- | ---: | ---: | --- |']
    for key,label in [('old-breathing-small lean','Original kick, 33 cubed'),('new-drive-even-gap','New even force, 49 cubed'),('new-drive-odd-lean','New odd force, 49 cubed')]:
        v=steps[key];d=v.get('kick_projection_onto_D',v.get('direct_D_force_at_second_stage'));kind='kick in D' if 'kick_projection_onto_D' in v else 'D rate at second stage';lines.append(f"| {label} | {v['dt']:.8f} | {v['first_difference_from_unforced']:.6g} | {d:.6g} ({kind}) |")
    lines+=['','The mirror-even kick changes the velocity field while its direct projection onto signed D is at roundoff. It can still affect later D through the changing fluid, and E through both its numerator and denominator. The odd force directly drives D. The two direct-contribution columns use different units because one is a velocity increment and the other a rate.','','The statement “breathing stops, therefore force was only applied at initialization” is not established. A measured response may weaken even while forcing continues. The actual loop confirms repeated application.','','## Early response','','![Early response](early-response.png)','','| Case | Slope window | E slope | D slope | W slope |','| --- | --- | ---: | ---: | ---: |']
    for k,label in [('mirror-49-1','Unforced lean, 49'),('new-drive-even-gap','New even force, 49'),('new-drive-odd-lean','New odd force, 49'),('old-breathing-small lean','Original kick, 33')]:
        v=hist[k]['slopes'];lines.append(f"| {label} | {v['window'][0]:.3f}–{v['window'][1]:.5f} | {v['E']:.6g} | {v['D']:.6g} | {v['W']:.6g} |")
    lines+=['','These are fitted slopes over saved observations, not instantaneous derivatives or growth exponents. All three 49-grid curves start from the same lean. The mirror-odd drive raises D and E in this early window while W still decreases. The source-only history has its first stored sample near time 0.1; it cannot supply equally fine early timing.','','## Reflection and numerical controls','','| Check | Largest first-step relative field discrepancy |','| --- | ---: |']
    for k,v in a['pairs'].items():lines.append(f"| {k} | {v['first_field_error']:.3g} |")
    comp=a['resolution']['mirror']['curve_comparisons'];g=comp['n49-s1-shape0-none-base vs n65-s1-shape0-none-base'];h=comp['n65-s1-shape0-none-base vs n65-s1-shape0-none-half']
    lines+=['','For the completed unforced lean controls through 0.4:','','| Refinement | W curve difference | E curve difference | D curve difference |','| --- | ---: | ---: | ---: |',f"| 49 to 65 cubed | {100*g['W']:.5f}% | {100*g['E']:.5f}% | {100*g['D']:.5f}% |",f"| 65 cubed, half timestep | {100*h['W']:.7f}% | {100*h['E']:.5f}% | {100*h['D']:.5f}% |",'','These are different measurements with different convergence behavior. Preserved reflection does not establish resolution of W. The completed [methods controls](../methods-controls/README.md) include spectra; the [adaptive peak audit](../../../../../reports/matched-stretch/adaptive-peak/README.md) contains physical core widths and high-wavenumber checks for the separate matched-stretch field.','','## Matched stretch','','The reconstructed 64-grid start matches its saved spectral field to roundoff. It begins at W = 59.27995 and kinetic energy 17545.88279, compared with W = 14.78380 and energy 4.60954 for the 33-grid AB reference. The fields, viscosity and grids differ. Their different later behavior does not isolate one causal change.','','The matched-stretch peak is near the periodic join, and the raw strain has a mismatch there. It is not established that the central tube is the location responsible for its largest peak. The original start still fails the six-cell width requirement on every audited grid. It remains a diagnostic of that supplied construction.','','## Files and scope','','[All measurements and source hashes](results.json) · [Audit code](audit.py) · [Plot code](report.py)','','Raw component arrays and restart fields remain with the local study because of their size; their hashes are recorded here. Measurement records, charts and code are on GitHub and in the local repository mirror. To rerun this audit with the saved arrays, install `requirements.txt` and run `python audit.py --study-root PATH_TO_MATCHED_STRETCH_STUDY`, followed by `python report.py`.','','Six original breathing first-step fields and two new-drive first-step measurement records were matched directly. The other first steps are diagnostic reconstructions: their starting fields or initial measurements were matched to saved data, and opposite-pair steps were compared. The included solver copies are unchanged. The audit exposes raw components, measures before and after projection, reconstructs the first step, reads early saved observations, checks reflected partners, and reuses refinement evidence. It does not assert a new smoothness theorem or a verified reduced-to-fluid model.','']
    (ROOT/'README.md').write_text('\n'.join(lines),encoding='utf-8')
    (ROOT/'requirements.txt').write_text('numpy\nscipy\nmatplotlib\n')
    print(json.dumps(dict(figures=2,report='README.md',first_steps=len(steps))))
if __name__=='__main__':main()
