"""Ground motion, pond response, and the limits of a synthetic calibration."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET


def render():
    root = Path(__file__).resolve().parent
    data = root/"data"/"pond-vibration"
    if not (data/"summary.json").exists():
        return ""
    result = json.loads((data/"summary.json").read_text())
    tests = list(ET.parse(data/"independent-tests.xml").getroot().iter("testcase"))
    failed = sum(t.find("failure") is not None or t.find("error") is not None for t in tests)
    rows = [r for r in result["cases"] if r["amplitude_m"] == .0001 and r["step_s"] in (.1, .025)]
    cells = "".join(f'<tr><td>{r["width_s"]:g} s</td><td>{r["step_s"]:g} s</td><td>{100*r["error_over_reference_peak"]:.5g}%</td><td>{"PASS" if r["accuracy_passed"] else "FAIL"}</td><td>{"PASS" if r["energy_budget_passed"] else "FAIL"}</td></tr>' for r in rows)
    return f'''<section id="pond-vibration"><h2>Can footsteps move a pond and its tiny inhabitants?</h2>
<p><strong>There is a physical path:</strong> impacts load the ground; ground deformation can disturb a pond's bed or banks; water motion can carry suspended particles. Many particles may move because they share the same moving water. That does not establish biological sensing, damage, collective decision-making or a planetary effect. Counts of organisms and counts of vibration sources are different quantities.</p>
<p><strong>The concert example is documented.</strong> Caltech and UCLA measured seismic motion associated with a crowd of more than 70,000 at a 2023 Taylor Swift show. Their study attributed the main signal to dancing and jumping. <a href="https://www.caltech.edu/about/news/swifities-shake-it-off-and-help-seismologists-solve-mystery-of-how-concertgoers-shake-things-up">Caltech's account</a>. PNSN explicitly says the Seattle concert did not cause or trigger an earthquake and cautions about assigning earthquake magnitudes to it. <a href="https://pnsn.org/blog/beast-quake-taylor-s-version-from-the-vault">PNSN's analysis</a>. These sources do not establish the claimed earthquake-alarm incident.</p>
<p><strong>Timing affects how contributions combine.</strong> For an idealized linear case, assume 64 equal contributions at the pond, all at one frequency and with equal coupling to the same water mode. In phase, their amplitude is 64 times one contribution. Independent uniformly random phases give a root-mean-square combined amplitude of 8 times one contribution; evenly spaced phases cancel ideally. These are analytical superposition results, not a crowd simulation or measured footstep gains. Propagation delays, ground properties, source spacing and damping determine the actual combination. Globally scattered footsteps cannot simply be counted as one synchronized source.</p>
<p><strong>Completed pond pilot:</strong> {len(result['cases'])} time-step comparisons, one zero-motion control, {result['checks_passed']}/{result['checks_total']} benchmark checks and {len(tests)-failed}/{len(tests)} independent tests. The basin is <em>assumed</em> to be 2 m long and 0.1 m deep, with drag 0.15 s⁻¹. Its first shallow-water mode has predicted period {result['natural_period_s']:.3f} s. Bed movement amplitudes of 10 and 100 µm, lasting 0.2 or 2 s, are chosen numerical inputs. They are not estimates of a particular footstep, rock impact, crowd or surveyed pond.</p>
<figure><img src="figures/10_pond_vibration.png" alt="Assumed short and long pond-bed pulses, predicted water response, and time-step error"><figcaption>The plotted 100 µm inputs are hypothetical bed motions. A genuine response to that input is separated from numerical error against an independent convolution reference. <a href="figures/10_pond_vibration.svg">SVG</a></figcaption></figure>
<p>At a fixed duration, ten times the bed movement produced ten times the response in this linear model. Duration changed the residual oscillation substantially: with a 100 µm bed pulse, the maximum surface-mode amplitude <em>after the pulse</em> was about 9.03 µm for 0.2 s and 84.23 µm for 2 s. The instantaneous peak while the bed was moving is a different metric, retained in the raw results.</p>
<div class="scroll"><table><thead><tr><th>Pulse duration</th><th>RK4 step</th><th>Numerical error / reference peak</th><th>0.1% surface target</th><th>Energy budget</th></tr></thead><tbody>{cells}</tbody></table></div>
<p>The 0.2 s pulse needed closer time resolution. At h=0.1 s, its sampled surface error was about 55%; at h=0.025 s it was about 0.069%. The 2 s pulse was already below 0.004% at h=0.1 s. Both amplitudes had essentially the same <em>relative</em> numerical error for a given pulse shape. Thus strength alone is not a time-step rule. The finest tested step, 0.00625 s, passed surface and energy budgets in all four input cases.</p>
<p>The equations are η<sub>t</sub>+H u<sub>x</sub>=b<sub>t</sub> and u<sub>t</sub>+gη<sub>x</sub>=−d u, with b=B(t)cos(πx/L). A single analytical spatial mode gives η=A(t)cos(πx/L), u=U(t)sin(πx/L), A′=B′−HkU and U′=gkA−dU. No water crosses the idealized ends. Volume conservation follows from this mode's zero spatial mean; it is not a general spatial-grid validation.</p>
<p>Energy per unit width is E=ρL(gA²+HU²)/4. Bed work and drag dissipation are integrated separately and checked against the change in E. The independent reference integrates the analytic damped-wave response using 64-point Gauss quadrature; 32-point comparison and an independently stepped DOP853 solution agree within their declared tolerances. Input timing is resolved explicitly to avoid skipping the pulse.</p>
<p><strong>Actual matching is still uncalibrated.</strong> It needs pond dimensions, source distance, soil/bank coupling, and a measured bed/bank displacement or velocity record with timing and uncertainty. Acceleration can help, but recovering displacement requires instrument correction and drift control. The <a href="https://local.scedc.caltech.edu/data/concert-tremor.html">SCEDC concert waveform archive</a> is real external evidence, not a measurement at this pond, and has not been fed into this pilot.</p>
<p class="small">The model omits local higher modes, horizontal bank motion, surface tension, vertical nonhydrostatic effects, wind, breaking, wetting/drying, soil elasticity and microbial response. Its spatial bed shape is a first-mode idealization, not a localized footprint. The shallow-water natural frequency differs from the corresponding finite-depth gravity-wave formula by about {100*result['shallow_frequency_relative_difference_from_finite_depth']:.2f}% for these assumed dimensions; smaller numerical steps do not remove that model discrepancy. No visible ripple, biological outcome or actual footstep strength is claimed. Deterministic inputs require no random seed; the random-phase comparison above is an analytical expectation, not sampled data.</p>
<p>Physical context: <a href="https://www.usgs.gov/programs/earthquake-hazards/seismic-seiches">USGS on seismic excitation of water bodies</a> and <a href="https://arxiv.org/abs/physics/0611182">linear theory of waves from moving bottoms</a>. Earthquake-scale evidence supports the coupling mechanism; it is not a calibration for footsteps.</p>
<p><a href="data/pond-vibration/cases.csv">20 numerical comparisons</a> · <a href="data/pond-vibration/summary.json">Responses, budgets and provenance</a> · <a href="data/pond-vibration/independent-tests.xml">Eight-test record</a> · <a href="pond_vibration_plan.json">Assumptions and missing measurements</a> · <a href="pond_vibration.py">Reproducible model</a></p></section>'''
