"""Generate scientific plots and a standalone readable HTML report from saved results."""
from pathlib import Path
import base64,csv,html,json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.ticker import NullLocator
from analyze import summarize
from simulate import dump

ROOT=Path(__file__).resolve().parent
LABELS={'main':'9 molecules, main','long':'9, longer run','size27':'27, one heavy','wall':'9, wider wall','halfdt':'9, half step','friction':'9, weaker thermostat'}
METRICS={'hb_degree':'H-bond degree','coordination':'Oxygen coordination','degree_sd':'Degree heterogeneity','nn_exchange':'Nearest-neighbor exchanges / ps','hb_rmst':'H-bond lifetime RMST / ps','residence_rmst':'Neighbor residence RMST / ps','hb_survival_05':'Continuous bond survival at 0.5 ps','response_offdiag':'Response at 0.5 ps (unreliable)','response_002':'Response at 0.02 ps','response_010':'Response at 0.1 ps','response_participation':'Response participation at 0.5 ps (unreliable)','response_far_share':'Far response fraction at 0.5 ps (unreliable)','rank_stability':'Early/late degree-rank correlation','nn_stride2':'Exchange rate sampled every 0.1 ps','hb_rmst_stride2':'H-bond lifetime sampled every 0.1 ps'}
def fmt(v):return f'{v:.5g}' if isinstance(v,(float,int)) else str(v)
def ci(s):return f"{fmt(s['mean'])} [{fmt(s['ci95'][0])}, {fmt(s['ci95'][1])}]"
def table(headers,rows):
    return '<div class="scroll"><table><thead><tr>'+''.join(f'<th>{html.escape(str(h))}</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def embed(name):return f'<img src="data:image/png;base64,{base64.b64encode((ROOT/name).read_bytes()).decode()}" alt="{name}">'
def savefig(fig,name):
    fig.savefig(ROOT/(name+'.png'),dpi=180,bbox_inches='tight');fig.savefig(ROOT/(name+'.svg'),bbox_inches='tight');plt.close(fig)

def main():
    s=json.loads((ROOT/'analysis/statistics.json').read_text());inv=json.loads((ROOT/'analysis/inventory.json').read_text());validation=json.loads((ROOT/'validation.json').read_text());ref=json.loads((ROOT/'refinement/summary.json').read_text());switch=json.loads((ROOT/'switch/summary.json').read_text());rr=json.loads((ROOT/'refinement/results.json').read_text())
    rows=list(csv.DictReader((ROOT/'analysis/trajectories.csv').open()));mol=list(csv.DictReader((ROOT/'analysis/molecules.csv').open()));mainrows=[r for r in rows if r['suite']=='main' and r['label']=='False']
    plt.rcParams.update({'font.family':'DejaVu Sans','axes.spines.top':False,'axes.spines.right':False,'font.size':10})
    suites=['main','long','size27','wall','halfdt','friction']
    fig,axs=plt.subplots(1,3,figsize=(13,4.8))
    for ax,key in zip(axs,['hb_degree','nn_exchange','hb_rmst']):
        for i,suite in enumerate(suites):
            z=s[suite]['mass'][key];base=z['baseline'];x=100*z['mean']/base;lo,hi=100*np.array(z['ci95'])/base
            ax.errorbar(x,i,xerr=[[x-lo],[hi-x]],fmt='o',capsize=3,color='#136e74')
        ax.axvline(0,color='#aaaaaa',ls='--',lw=1);ax.set_yticks(range(len(suites)),[LABELS[k] for k in suites]);ax.invert_yaxis();ax.set_xlabel('Change relative to all-light baseline (%)');ax.set_title(METRICS[key]);ax.grid(axis='x',alpha=.15)
    fig.suptitle('Mass-only substitution: trajectory statistics and 95% cluster-bootstrap intervals',y=1.03)
    fig.tight_layout();savefig(fig,'effects')
    # All nine initial placement effects, paired by configuration and velocity.
    fig,axs=plt.subplots(1,2,figsize=(10,4.2))
    for ax,key in zip(axs,['hb_degree','nn_exchange']):
        values=[]
        for h in range(9):
            deltas=[]
            for c in range(16):
                ar=[r for r in mainrows if int(r['config'])==c and int(r['heavy'])==-1];ds=[r for r in mainrows if int(r['config'])==c and int(r['heavy'])==h]
                deltas.append(np.mean([float(x[key])-float(next(a for a in ar if a['velocity']==x['velocity'])[key]) for x in ds]))
            z=summarize(deltas);values.append(z)
        mean=np.array([z['mean'] for z in values]);lower=np.array([z['ci95'][0] for z in values]);upper=np.array([z['ci95'][1] for z in values])
        ax.errorbar(range(9),mean,yerr=[mean-lower,upper-mean],fmt='o',color='#136e74',capsize=3);ax.axhline(0,color='gray',lw=1);ax.set_xlabel('Initial radial rank (0 inner, 8 outer)');ax.set_title(METRICS[key]);ax.set_ylabel('D at site minus all-light group')
    fig.suptitle('Starting placement is an initial condition, not a permanent seat',y=1.03);fig.tight_layout();savefig(fig,'positions')
    # Numerical convergence and refined short-time transmission.
    fig,axs=plt.subplots(1,3,figsize=(13,4.1))
    for name,label,color in [('step_025_to_0125','Time step halved','#136e74'),('impulse_0125_to_00625','Kick halved','#b06f2b')]:
        x=np.array([e['relative_by_lag'][1:] for e in ref['errors'] if e['check']==name]);axs[0].plot([.02,.1,.5],100*x.max(axis=0),'o-',label=label,color=color)
    axs[0].set_xscale('log');axs[0].set_yscale('log');axs[0].set_xlabel('Response lag (ps)');axs[0].set_ylabel('Largest matrix change (%)');axs[0].set_title('Convergence depends on lag');axs[0].legend(fontsize=8)
    axs[0].set_xticks([.02,.1,.5],['0.02','0.1','0.5']);axs[0].xaxis.set_minor_locator(NullLocator())
    fine=[r for r in rr if r['dt']==.000125 and r['j']==.00625]
    avg=np.mean([r['matrices'][1] for r in fine if r['heavy']==-1],axis=0)
    im=axs[1].imshow(avg*1e5,cmap='viridis');fig.colorbar(im,ax=axs[1],shrink=.8,label='Response (10⁻⁵ ps / dalton)');axs[1].set_xlabel('Target molecule');axs[1].set_ylabel('Perturbed source');axs[1].set_title('0.02 ps: all-light mean')
    loc={};keys=['group','heavy_out','heavy_in','untagged_to_untagged'];basevals={k:[] for k in keys};dvals={k:[] for k in keys};far=[];part=[]
    for c in range(8):
        a=next(r for r in fine if r['config']==c and r['heavy']==-1);amat=np.array(a['matrices'][1]);ds=[r for r in fine if r['config']==c and r['heavy']>=0];per={k:[] for k in keys};pb={k:[] for k in keys}
        q=np.load(ROOT/f'data/main_c{c:02d}_v0_A.npz')['snapshot_q_nm'][1,::3];dist=np.linalg.norm(q[:,None]-q[None,:],axis=-1)
        far.append(float((amat*(dist>.35)).sum()/amat.sum()));part.append(float(np.mean(amat.sum(axis=1)**2/np.maximum((amat**2).sum(axis=1),1e-40))))
        for r in ds:
            h=r['heavy'];b=np.array(r['matrices'][1]);mask=np.ones((9,9),bool);np.fill_diagonal(mask,False);remote=mask.copy();remote[h,:]=False;remote[:,h]=False
            for key,ix in [('group',mask),('heavy_out',mask & (np.arange(9)[:,None]==h)),('heavy_in',mask & (np.arange(9)[None,:]==h)),('untagged_to_untagged',remote)]:
                per[key].append((b-amat)[ix].mean());pb[key].append(amat[ix].mean())
        for k in keys:dvals[k].append(np.mean(per[k]));basevals[k].append(np.mean(pb[k]))
    for i,k in enumerate(keys):
        loc[k]=summarize(dvals[k],basevals[k]);z=loc[k];base=z['baseline'];m=z['percent'];l,h=100*np.array(z['ci95'])/base
        axs[2].errorbar(m,i,xerr=[[m-l],[h-m]],fmt='o',capsize=3,color='#136e74')
    axs[2].set_yticks(range(4),['Whole group','Heavy source','Heavy target','Other to other']);axs[2].invert_yaxis();axs[2].axvline(0,color='gray',lw=1);axs[2].set_xlabel('Matched-state response change (%)');axs[2].set_title('0.02 ps: where change occurs')
    fig.tight_layout();savefig(fig,'response')
    loc.update(far_response_fraction=summarize(far),effective_participation=summarize(part));dump(ROOT/'analysis/refined_locality.json',loc)
    effect_checks=[]
    for dt,j in [(.00025,.0125),(.000125,.0125),(.000125,.00625)]:
        settings=[r for r in rr if r['dt']==dt and r['j']==j];ds={k:[] for k in keys}
        for c in range(8):
            a=np.array(next(r for r in settings if r['config']==c and r['heavy']==-1)['matrices'][1]);per={k:[] for k in keys}
            for r in [r for r in settings if r['config']==c and r['heavy']>=0]:
                h=r['heavy'];b=np.array(r['matrices'][1]);mask=~np.eye(9,dtype=bool);remote=mask.copy();remote[h,:]=False;remote[:,h]=False
                for key,ix in [('group',mask),('heavy_out',mask & (np.arange(9)[:,None]==h)),('heavy_in',mask & (np.arange(9)[None,:]==h)),('untagged_to_untagged',remote)]:per[key].append((b-a)[ix].mean())
            for k in keys:ds[k].append(np.mean(per[k]))
        effect_checks.append(dict(dt_ps=dt,impulse=j,mean_effect={k:float(np.mean(v)) for k,v in ds.items()}))
    dump(ROOT/'analysis/refined_effect_convergence.json',effect_checks)
    fig,axs=plt.subplots(1,2,figsize=(10,4))
    for suite in ['main','long']:
        paths=sorted((ROOT/'data').glob(f'{suite}_c*_v*_A.npz'));lines=[]
        for p in paths:
            z=np.load(p);temp=2*z['energies_kjmol'][:,1]/(.00831446261815324*54);length=(len(temp)-1)*.05;trim=temp[:-1].reshape(-1,100).mean(axis=1);lines.append(trim)
        lines=np.array(lines);axs[0].plot((np.arange(lines.shape[1])+.5)*5,lines.mean(axis=0),label=LABELS[suite])
    axs[0].axhline(300,color='gray',ls='--',lw=1);axs[0].set_xlabel('Production time (ps)');axs[0].set_ylabel('5 ps temperature mean (K)');axs[0].legend();axs[0].set_title('All-light ensemble temperature')
    values=[float(r['rank_stability']) for r in mainrows if int(r['heavy'])==-1];axs[1].hist(values,bins=np.linspace(-1,1,11),color='#136e74',alpha=.85);axs[1].set_xlabel('First-half vs second-half degree-rank correlation');axs[1].set_ylabel('All-light trajectories');axs[1].set_title('Rank persistence varies between trajectories')
    fig.tight_layout();savefig(fig,'diagnostics')
    mass=s['main']['mass'];primary=['hb_degree','nn_exchange','response_offdiag']
    primarytable=table(['Declared primary measure','All-light mean','D minus H [95% CI]','Change','Cluster dₕ','Holm p'],[[METRICS[k],fmt(mass[k]['baseline']),ci(mass[k]),fmt(mass[k]['percent'])+'%',fmt(mass[k]['dz']),fmt(mass[k]['holm_p'])] for k in primary])
    secondarytable=table(['Measure','All-light mean','D minus H [95% CI]'],[[METRICS[k],fmt(v['baseline']),ci(v)] for k,v in mass.items() if k not in primary])
    counttable=table(['Completed suite','Trajectories','Independent starting configurations','Equilibration + production'],[[LABELS[k],inv['counts'][k],16 if k=='main' else 4 if k in ['halfdt','friction'] else 8,'50 + 100 ps' if k not in ['long','size27'] else '100 + 300 ps' if k=='long' else '100 + 100 ps'] for k in suites])
    interact=table(['Measure','D at inner minus D at outer [95% CI]'],[[METRICS[k],ci(s['main']['initial_position_interaction'][k])] for k in ['hb_degree','nn_exchange','hb_rmst','response_002']])
    tagged=table(['Tagged / remote measure','Mass effect [95% CI]','Mass x initial-position effect [95% CI]'],[[k,ci(v['mass']),ci(v['mass_position'])] for k,v in s['main']['tagged'].items()])
    sensitivity=table(['Changed condition','Measure','Change in mass effect vs matched main extremes [95% CI]'],[[LABELS[k],METRICS[m],ci(z)] for k in suites[1:] for m,z in s[k]['paired_sensitivity_shift'].items() if m in ['hb_degree','nn_exchange','hb_rmst']])
    diag=table(['Suite','Temperature K [95% CI]','Second minus first half H-bond degree [95% CI]','Potential shift kJ/mol/molecule [95% CI]'],[[LABELS[k],ci(s['diagnostics'][k]['temperature_K']),ci(s['diagnostics'][k]['hb_second_minus_first']),ci(s['diagnostics'][k]['potential_second_minus_first'])] for k in suites])
    errors=table(['Refinement check','Largest change: 0.02 ps','0.1 ps','0.5 ps'],[[name,*[fmt(100*v)+'%' for v in np.max([e['relative_by_lag'][1:] for e in ref['errors'] if e['check']==name],axis=0)]] for name in ['step_025_to_0125','impulse_0125_to_00625']])
    refine_table=table(['Matched-state 0.02 ps measure','Difference [95% CI]','Relative difference'],[[k,ci(loc[k]),fmt(loc[k]['percent'])+'%'] for k in keys])
    nve=max(float(r['response_nve_energy_range']) for r in rows if r.get('response_nve_energy_range'));top=np.mean([float(r['top_repeat']) for r in mainrows if int(r['heavy'])==-1])
    hb=mass['hb_degree'];nn=mass['nn_exchange'];remote=s['main']['tagged']['remote_hb_degree']['mass']
    conclusion=f"Across all nine placements, the mean H-bond degree changed by {fmt(hb['mean'])} ({fmt(hb['percent'])}%; 95% interval {fmt(hb['ci95'][0])} to {fmt(hb['ci95'][1])}). Nearest-neighbor exchange changed by {fmt(nn['mean'])} per ps ({fmt(nn['percent'])}%; interval {fmt(nn['ci95'][0])} to {fmt(nn['ci95'][1])}). Interpret these model estimates with the sensitivity tables below. The declared 0.5 ps response endpoint failed numerical checks."
    body=f'''<header><p class="eyebrow">NousVolition / My-Sources-Project-ALL · completed exploratory MD</p><h1>A heavier molecule<br>in a group of nine</h1><p class="subtitle">A reproducible mass-only isotope test with explicit water interactions, randomized ensembles and intervention-based response measurements.</p></header>
<section class="callout"><h2>What this test establishes</h2><p>{conclusion}</p><p><strong>There is a measurable short-time inertial response in the refined matched-state assay, concentrated in interactions involving the substituted molecule. This does not establish collective reorganization or a persistent leader.</strong> All findings concern confined, classical TIP3P water. They do not establish an isotope effect in real liquid water.</p></section>
<h2>What actually ran</h2><p>{inv['completed']} full trajectories completed: 32 all-light and 288 single-heavy main trajectories, 32 repeated label controls, and 192 sensitivity trajectories. The main ensemble has 16 independent randomized configurations, each with two velocity/thermostat seeds. Repeated frames, molecules, isotope placements and shared-start velocity seeds are not counted as independent initial configurations.</p>{counttable}<p>Also completed: 160 same-state mass-switch assays, 16 initial response sensitivity checks, and 72 finer-step / smaller-kick response assays. The last set was added after the long-lag check failed and is explicitly exploratory. All branch coordinates and the failures are retained.</p>
<h2>The model and its boundary</h2><p>Each molecule has one oxygen and two hydrogen sites, rigid TIP3P geometry, oxygen Lennard-Jones interactions and Coulomb interactions between partial charges. No interaction cutoff or periodic replicas are used. A flat-bottom spherical wall acts on oxygens: U<sub>wall</sub> = (10000/2) max(0, r − R)² kJ/mol, with r and R in nm. R = 0.4 nm for nine molecules; the 27-molecule radius is 0.4 × 3<sup>1/3</sup> nm. A separate test uses R = 0.5 nm.</p><p>The wall prevents indefinite dispersal of a tiny warm cluster. It supplies external forces and breaks translational momentum conservation. This is a model of confined water with strong finite-size and surface effects; it is not a nine-particle sample of bulk liquid. Whole-group membership is fixed. “Residence time” below means time inside another oxygen’s neighbor shell, not residence in the entire group.</p><p>The engine is OpenMM 8.6.1 Reference (double precision). All simulations use 300 K LangevinMiddle temperature control, independent seed blocks, minimization, equilibration and rigid constraints at 10<sup>−8</sup>. The main time step is 1 fs and friction is 1 ps<sup>−1</sup>. The thermostat affects dynamical rates; weaker-friction and half-step tests are included. Production coordinates and energies are saved every 0.05 ps. Details, seeds and exact units are in <a href="protocol.json">protocol.json</a> and the raw metadata.</p><p>The oxygen mass is 15.99943 Da; hydrogen is 1.007947 Da and deuterium 2.01410177812 Da. Only the two hydrogen masses of the selected molecule change. The mass increase for the whole D₂O molecule is about 11.2%, so this is not an infinitesimal perturbation. Charges, Lennard-Jones parameters, bond lengths, angles and wall forces are identical. Atom labels remain water labels; physical masses define the isotope model.</p>
<h2>Organization and dynamics</h2><p>A hydrogen-bond edge exists when O–O is below 0.35 nm and a donor O–H···O angle is at least 150°. Either donating direction produces one undirected edge. This geometric edge is not a covalent bond. Oxygen coordination uses the same distance without the angular test. Degree is the number of incident edges; structural centrality is the normalized principal eigenvector of the trajectory-average adjacency matrix.</p><p>Nearest-neighbor exchange counts changes of the nearest oxygen at consecutive saved frames, including recrossings. H-bond and shell-residence lifetimes use newly observed episodes, excluding episodes already active at the start and retaining right censoring at the end. Kaplan–Meier restricted mean lifetime integrates survival to 2 ps. They are distinct from the probability that an occupied bond survives without interruption for 0.5 ps. Reformations count as new episodes. These definitions follow the need to separate continuous and intermittent bond dynamics discussed by <a href="https://www.nature.com/articles/379055a0">Luzar and Chandler (1996)</a>.</p>{primarytable}<p>Intervals resample whole starting-configuration clusters 10000 times. Within a cluster, treatment and control share the configuration and velocity/noise seed; isotope placements and the two seeds are averaged before resampling. d<sub>z</sub> is the paired difference divided by its between-configuration SD. Sign-flip tests assume symmetric independent cluster differences; they are not an exact treatment-randomization guarantee. Holm adjustment covers the three declared primary outcomes only. All other intervals and follow-up tests are exploratory, unadjusted and limited by 4–16 independent configurations. A confidence interval containing zero does not establish equivalence.</p>{embed('effects.png')}<p>The main row averages all nine isotope sites; sensitivity rows average the initially inner and outer sites only. Matched comparisons below explicitly use those same extremes in the main data. Larger groups also dilute the isotope: 1/9 versus 1/27, so size and concentration are not separated.</p><details><summary>All secondary group measures</summary>{secondarytable}</details>
<h2>Position, identity and local versus collective change</h2><p>Sites are numbered by increasing distance from the center in each randomized initial packing. All nine sites receive the heavy isotope in separate paired runs. Minimization and equilibration allow molecules to exchange positions: initial rank is not a maintained spatial role. A reproducible early-to-late positional effect would require additional evidence.</p>{embed('positions.png')}{interact}{tagged}<p>Remote network structure uses only edges between untagged molecules. Its main mass effect is {ci(remote)} degree units. A group mean can change solely because the tagged molecule changes; that alone is not evidence for a collective hierarchy. The same all-light trajectory with randomly reassigned identities gives a maximum coordinate mismatch of {fmt(inv['max_label_error_nm'])} nm after undoing the permutation, across {inv['label_controls']} controls. A separate reordered-particle NVE test checks physical permutation symmetry. Identities have no independent causal force in this model.</p>
<h2>A causal response assay, with a failed long-lag check</h2><p>At three production snapshots, each source receives equal and opposite total momentum kicks of magnitude 0.05 Da nm/ps along each Cartesian axis. All atoms of the source receive the same added velocity, preserving rigid constraints. Paired branches evolve without thermostat for lags 0, 0.02, 0.1 and 0.5 ps. R<sub>ij</sub> is the root mean square over axes of the central difference in target oxygen position divided by twice the impulse. Units are ps/Da. Off-diagonal R measures transmitted response; direct self-motion is excluded. Kicks have equal momentum, not equal energy. The measure is conditional on the state, intervention and observation time.</p><p><strong>The original 0.5 ps endpoint is not numerically reliable.</strong> Halving the original step or kick changed some response matrices substantially. A further test at 0.25 and 0.125 fs and impulses 0.0125 and 0.00625 Da nm/ps still leaves the 0.5 ps endpoint sensitive. The response means and ranks at that lag are saved for audit, not accepted as evidence of influence ordering. Maximum unperturbed 0.5 ps energy range over the production snapshots was {fmt(nve)} kJ/mol; energy stability alone does not guarantee response convergence.</p>{errors}{embed('response.png')}<p>The refined shorter-lag analysis uses eight all-light states with identical coordinates and velocities across A, D at site 0 and D at site 8. Switching masses at fixed velocity changes kinetic energy, so these are conditional interventions, not equilibrium trajectories. The 0.02 ps effect is {ci(ref['matched_state_effects']['response_002'])} ps/Da. The point estimate is {fmt(loc['group']['percent'])}% of the matched all-light response. This is a numerical demonstration of altered short-time transmission in the model.</p>{refine_table}<p>At 0.02 ps, the mean response fraction reaching targets initially farther than 0.35 nm is {fmt(100*loc['far_response_fraction']['mean'])}%, with effective participation {fmt(loc['effective_participation']['mean'])} of eight possible other molecules. Long-range electrostatics can transmit weak response beyond a contact edge. The larger changes involving the heavy source/target and the untagged-to-untagged estimate above distinguish local inertia from collective reorganization. The full all-nine switch assay and 0.1 ps exploratory estimates are retained in the data, including their uncertainty.</p>
<h2>Persistence and sensitivity</h2><p>For all-light main trajectories, the molecule with the highest mean degree in the first half also has the highest mean degree in the second half in {fmt(100*top)}% of trajectories. This is descriptive, not a test against a 1/9 null: time windows are correlated and labels began in different configurations. Degree-rank correlations are shown below. Finite-window centrality or response differences do not demonstrate a persistent leader; a reliable leader claim would require sustained, independently validated intervention effects across times, permutations, sites and model choices.</p>{embed('diagnostics.png')}{diag}<p>Temperature and early/late energy/network checks assess gross drift; they do not prove equilibrium or mixing of every slow variable. The longer runs double equilibration and triple production. Full sensitivity differences are reported, including those inconsistent with the main estimate.</p><details><summary>Paired sensitivity changes in the estimated mass effect</summary>{sensitivity}</details><p>Sampling sensitivity doubles the observation interval from 0.05 to 0.1 ps using the same saved trajectories. It is not a separate replicate. Absolute bond lifetimes and exchange rates depend on how short recrossings are resolved; raw data support alternative definitions.</p>
<h2>What remains untested</h2><ul><li>Bulk water with periodic PME and validated system-size, concentration and long-time convergence; a constant-fraction comparison with three heavy molecules among 27.</li><li>Independent force fields, a wall-free low-temperature cluster ensemble, sub-50-fs contact sampling and substantially more independent configurations.</li><li>Nuclear quantum effects, flexible anharmonic O–H/O–D vibrations, polarizability, isotope exchange chemistry and real experimental validation.</li><li>A converged long-lag causal-response network, a persistent leader, and any extrapolation to Navier–Stokes physics or evolutionary change in H₂O.</li></ul><p>At fixed interaction potential, the classical equilibrium positional density is proportional to exp(−U/kT); integrating momenta yields mass factors that cancel upon normalization. Independent rigid molecules likewise contribute constant mass/inertia factors. Thus a reproducible structural isotope effect at classical equilibrium would require scrutiny of equilibration, sampling, constraints or a changed potential. Quantum nuclei need not obey this mass independence. Recent <a href="https://pubmed.ncbi.nlm.nih.gov/39607891/">path-integral water research</a> finds isotope effects especially important for dynamics. This calculation includes classical inertia but omits those quantum effects.</p>
<h2>Reproduce and inspect</h2><p>Use Python 3.12 with <a href="requirements.txt">the pinned dependencies</a>. Run <code>python test_science.py</code>, <code>python simulate.py --workers 4</code>, <code>python switch_assay.py</code>, <code>python refine_response.py</code>, <code>python analyze.py</code>, <code>python make_report.py</code>, and <code>python verify_results.py</code>, in that order. Windows users can run <a href="reproduce.ps1">reproduce.ps1</a>. Existing trajectory records are resumed; use an empty data directory for a fresh simulation. Same-platform seeded Reference runs are reproducible, but exact bitwise agreement across software/platforms is not promised.</p><p>The archive includes scripts, exact protocol, 544 raw trajectory archives, response branches, XML systems, seeds, trajectory/molecule CSVs, bootstrap cluster values, machine-readable results, numerical failures and SHA-256 provenance. The repository tracks scripts and compact results; the larger raw NPZ files remain in the local research directory and the delivered archive.</p><p>Existing project context: <a href="../../matched-stretch/marker-stress/README.md">passive-marker stress study</a> follows dX/dt=u(X,t); its labels have no molecular forces, inertia or thermal degrees of freedom. The local preceding water study used 216 rigid TIP3P molecules and three short runs but did not substitute isotopes. Neither source is pooled into this study’s evidence. The repository base and context hashes are recorded in provenance.</p><p>Implementation references: <a href="https://docs.openmm.org/latest/userguide/application/02_running_sims.html">OpenMM water models and constraints</a>; <a href="https://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinMiddleIntegrator.html">LangevinMiddle integration</a>; <a href="https://doi.org/10.1063/1.445869">original TIP3P paper</a>. These justify method definitions, not the empirical conclusions of this new model experiment.</p>
<footer>Completed tests and proposed extensions are separated throughout. No claim of new Navier–Stokes physics, molecular intention, or evolution of the water molecule.</footer>'''
    secondary_note=f"<p><strong>Secondary signals are not uniformly null.</strong> The main oxygen-coordination difference is {ci(mass['coordination'])}, and degree heterogeneity is {ci(mass['degree_sd'])}. Their unadjusted intervals exclude zero, but both signs reverse in the longer-run point estimates and their longer-run intervals include zero. The longer run shows a small exchange-rate reduction ({ci(s['long']['mass']['nn_exchange'])} per ps), while the main interval includes zero. N=27 shows a positive H-bond-degree interval, but also a potential-energy drift. These exploratory signals do not establish a stable collective structural effect. The primary 0.5 ps response has a nominal Holm p of {fmt(mass['response_offdiag']['holm_p'])}, but fails the numerical checks and cannot support a scientific significance claim.</p>"
    body=body.replace('<details><summary>All secondary group measures</summary>',secondary_note+'<details><summary>All secondary group measures</summary>')
    drift=f"<p><strong>Equilibration caveat:</strong> N=27 all-light potential energy shifts by {ci(s['diagnostics']['size27']['potential_second_minus_first'])} kJ/mol per molecule between production halves. The half-step pilot also has an interval excluding zero. These drift diagnostics prevent treating every suite as demonstrably equilibrated. Longer runs and stronger mixing diagnostics remain necessary before an equilibrium structural claim.</p>"
    body=body.replace('<details><summary>Paired sensitivity changes',drift+'<details><summary>Paired sensitivity changes')
    convergence_table=table(['Step (fs)','Impulse (Da nm/ps)','Group effect at 0.02 ps','Other-to-other effect'],[[fmt(r['dt_ps']*1000),fmt(r['impulse']),fmt(r['mean_effect']['group']),fmt(r['mean_effect']['untagged_to_untagged'])] for r in effect_checks])
    body=body.replace('<h2>Persistence and sensitivity</h2>', '<p>Because the remote effect is small, the effect differences themselves are compared under numerical refinement below; numerical stability does not turn a small conditional response into a persistent group hierarchy.</p>'+convergence_table+'<h2>Persistence and sensitivity</h2>')
    body=body.replace('<h2>Reproduce and inspect</h2>',f"<h2>Reproduce and inspect</h2><p>{validation['tests_run']} implementation tests passed: isotope force invariance, hydrogen-bond geometry, episode censoring, light and heavy molecular-identity permutations, cluster inference and absence of transmitted response when intermolecular forces are removed (several checks share one test). These checks are separate from the failed scientific long-lag convergence check. Full artifact verification also checks raw inventories, rigid geometry, saved data and relabeled network/response statistics.</p>")
    body=body.replace('../../matched-stretch/marker-stress/README.md','https://github.com/NousVolition/My-Sources-Project-ALL/blob/17c14e89940d4c96ec9df315b1a689430d8c5ddf/reports/matched-stretch/marker-stress/README.md')
    css='''body{max-width:1120px;margin:auto;padding:45px 32px 70px;font:17px/1.65 system-ui,sans-serif;color:#172b35;background:#fbfaf7}header{padding:30px 0 24px;border-bottom:3px solid #136e74}h1{font-size:58px;line-height:1.08;letter-spacing:-2px;margin:18px 0}h2{font-size:27px;line-height:1.3;margin-top:42px}p{max-width:100ch}.eyebrow{color:#136e74;text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:700}.subtitle{font-size:22px;max-width:850px;color:#49616b}.callout{background:#e7f0ee;border-left:5px solid #136e74;padding:4px 26px 16px;margin:30px 0}.callout h2{margin-top:22px}img{width:100%;height:auto;margin:20px 0;background:white}table{border-collapse:collapse;width:100%;font-size:13px;background:white;margin:20px 0}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #dce1df;vertical-align:top}th{background:#e7efed}.scroll{overflow:auto}a{color:#086c78}code{font-size:13px;background:#e8e9e5;padding:3px 5px}details{padding:10px 16px;background:#f0f1ed;margin:20px 0}summary{cursor:pointer;font-weight:600}footer{border-top:1px solid #c8d4d2;margin-top:45px;padding-top:20px;color:#566971;font-size:14px}@media(max-width:700px){body{padding:18px}h1{font-size:40px}table{font-size:12px}}'''
    (ROOT/'report.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A heavier molecule in a group of nine</title><style>'+css+'</style><body>'+body+'</body></html>',encoding='utf-8')
    readme=f'''# One heavy water molecule: completed explicit-MD model test

**[Read the full results](report.html)** · [Protocol](protocol.json) · [Statistics](analysis/statistics.json) · [Checks](validation.json)

{conclusion}

The refined 0.02 ps matched-state response changes by {ci(ref['matched_state_effects']['response_002'])} ps/Da ({fmt(loc['group']['percent'])}% relative). This demonstrates a small conditional inertial response in this confined classical model, not a persistent leader or evidence about real liquid water. The untagged-to-untagged response effect is {ci(loc['untagged_to_untagged'])} ps/Da.

## Completed

- 544 full trajectories: 16 random starting configurations x 2 velocity/noise seeds x (all-light + all nine heavy placements + label control), plus 192 sensitivity trajectories.
- Explicit rigid TIP3P interactions, changed isotope masses only, 300 K temperature control and 50–100 ps equilibration.
- Main production 100 ps; longer production 300 ps; N=27, confinement, timestep and friction checks.
- Hydrogen-bond networks, lifetimes with censoring, coordination, neighbor exchange, shell residence, structural centrality, label controls and cluster-bootstrap inference.
- 160 conditional mass-switch assays, 16 initial response checks and 72 refinement assays. The 0.5 ps response check failed and remains reported as unreliable.

## Reproduce

Python 3.12: install `requirements.txt`, then run `test_science.py`, `simulate.py --workers 4`, `switch_assay.py`, `refine_response.py`, `analyze.py`, `make_report.py`, `verify_results.py`. Windows: `./reproduce.ps1`. Reanalysis only: `python analyze.py` and `python make_report.py` on the extracted full archive.

Raw NPZ files are kept in the local research folder and full delivery archive; Git tracks scripts, metadata, compact results, plots and provenance. `verify_results.py --compact` validates tracked files without raw data. See `raw_manifest.json` for expected raw hashes. `protocol.json` was written before the ensemble execution; refinements and coarser-sampling checks are explicitly follow-ups.

## Limits

This is an exploratory **confined explicit-water MD model**, not a passive-tracer simulation or a validated bulk-water isotope calculation. A spherical oxygen wall is part of the Hamiltonian. With nine molecules there are major boundary effects. One heavy molecule among 27 also changes concentration. Classical mass substitution omits quantum nuclear/vibrational effects and isotope exchange chemistry. Same-potential classical equilibrium structure is mass independent; finite-time structural differences require sampling and convergence checks. A D2O molecule is about 11.2% heavier, not an infinitesimal change.

No persistent leader, new Navier–Stokes physics or evolutionary change in H2O is established. Proposed bulk, quantum, alternate-force-field and long-lag response validation is **not completed**.

## Project context

The [existing passive-marker study](../../matched-stretch/marker-stress/README.md) prescribes motion through a fluid field; its markers are not molecules. The preceding local 216-water TIP3P study is context only; its protocol and result hashes are recorded in `provenance.json`. This study was based on project commit `17c14e89940d4c96ec9df315b1a689430d8c5ddf` in an isolated local branch.
'''
    (ROOT/'README.md').write_text(readme,encoding='utf-8')
    print('Wrote report, README, 4 plot pairs and refined locality statistics.',flush=True)

if __name__=='__main__':main()
